### ISSUE TITLE
Don't create machine parts until deconstruction

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/dev-cycles-initiative#1]
Every machine initializes all of its machine parts immediately.

### Estimated Cost
`/obj/item/circuitboard/machine/apply_default_parts` is 280ms.

### Solutions
Machine parts should be instantiated only when necessary. This in and of itself is simple enough, however an issue arises with an extremely common pattern of:

```dm
for (var/obj/item/stock_parts/capacitor/capacitor in machine_parts)
    power += capacitor.capacitating_power
```

This pattern is seen for every stock part. You could change a lot of this by turning them into datums, and then a find-and-replace should work, but it makes the change tricky.

Power cells would likely need to always exist.

**Comment by Mothblocks** [comment]
Stock part datums: https://github.com/tgstation/tgstation/pull/71693

**Comment by SyncIt21** [comment]
So can we close this now?

**Comment by Mothblocks** [comment]
Yes thank you
