### ISSUE TITLE
Cable Connections are INCREDIBLY dumb

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/dev-cycles-initiative#16]
Cables connect VISUALLY with machines by looping objects in adjacent turfs inside UPDATE_ICON_STATE

Wastes cpu time, machines should just mark the cable below them

Similar vein. When connecting cables for the powernet, each pair of cables call update_appearance on each other. A-B is the same as B-A but both operations still happen. We should batch the appearance updates during init, and introduce some sort of state timer like atmos uses, so a cable will know just to not talk to its neighbor since it won't do anything interesting.

**Comment by Mothblocks** [comment]
`/obj/structure/cable/proc/Connect_cable` is 479.5ms.

**Comment by Mothblocks** [comment]
After https://github.com/tgstation/tgstation/pull/71703:

- `Connect_cable` = 479.5 -> 48.4
- `cable/Initialize` = 736.54 -> 290.32 (because of Connect_cable)
- `cable/LateInitialize` = new 149.44ms cost.

Other optimizations can be made, but this should be solved.
